# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               _gray.ish
tagline:             'blog'
description:         ''
url:                 https://sthkindacrazy.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Gray Shin
  url:
  email:             shinjoohyung25@gmail.com

# Custom vars
version:             1.0.0
