theme: jekyll-theme-minimal

title: continuous learning model
email: shinjoohyung25@gmail.com
description: newbie developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sthkindacrazy
