# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               _gray.ish
tagline:             Joohyung's blog
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joohyung Shin
  url:               sthkindacrazy.github.io
  email:             shinjoohyung25@gmail.com

# Custom vars
version:             1.0.0
